name: tyamo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  rounded_loading_button: ^2.1.0
  circular_profile_avatar: ^2.0.5
  getwidget: ^4.0.0
  page_transition: ^2.1.0
  responsive_sizer: ^3.3.0+1
  animated_bottom_navigation_bar: ^1.3.2
  font_awesome_flutter: ^10.7.0
  sleek_circular_slider: ^2.0.1
  awesome_dialog: ^3.2.0
  flutter_staggered_grid_view: ^0.4.1
  focused_menu: ^1.0.5
  flutter_balloon_slider: ^0.1.1
  expandable_text: ^2.3.0
  list_tile_more_customizable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
